language: python

jobs:
  include:
    # perform a linux build
    - services: docker

install:
  - python3 -m pip install cibuildwheel==1.3.0

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse

