language: python

jobs:
  include:
    # perform a linux build
    - services: docker

before_install:
  - sudo apt-get install zlib1g-dev zlib1g

install:
  - python3 -m pip install cibuildwheel==1.3.0

script:
  - export CIBW_BEFORE_BUILD="pip install cython && sudo apt-get install zlib1g-dev"
   # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse

